# Fail if any command fails
set -e

# Stats file used is the default for Toradocu
STATS_FILE=results.csv

if [ -f $STATS_FILE ]; then
    rm -i $STATS_FILE # Remove old stats file (if user agrees)
fi

if [ ! -f $STATS_FILE ]; then
    echo "METHOD,DISTANCE THRESHOLD,REMOVAL COST,\
CORRECT THROWS CONDITIONS,WRONG THROWS CONDITIONS,MISSING THROWS CONDITIONS,THROWS PRECISION,THROWS RECALL,\
CORRECT PARAM CONDITIONS,WRONG PARAM CONDITIONS,MISSING PARAM CONDITIONS,PARAM PRECISION,PARAM RECALL,\
CORRECT RETURN CONDITIONS,WRONG RETURN CONDITIONS,MISSING RETURN CONDITIONS,RETURN PRECISION,RETURN RECALL,\
CORRECT CONDITIONS,WRONG CONDITIONS,MISSING CONDITIONS,PRECISION,RECALL" > $STATS_FILE
fi

# Run Toradocu and collect statistics
./gradlew precisionRecallV01 --rerun-tasks
echo "TOTAL,,,\
=SUM(D1:INDIRECT(\"D\" & ROW()-1)),=SUM(E1:INDIRECT(\"E\" & ROW()-1)),=SUM(F1:INDIRECT(\"F\" & ROW()-1)),,,\
=SUM(I1:INDIRECT(\"I\" & ROW()-1)),=SUM(J1:INDIRECT(\"J\" & ROW()-1)),=SUM(K1:INDIRECT(\"K\" & ROW()-1)),,,\
=SUM(N1:INDIRECT(\"N\" & ROW()-1)),=SUM(O1:INDIRECT(\"O\" & ROW()-1)),=SUM(P1:INDIRECT(\"P\" & ROW()-1)),,,\
=SUM(S1:INDIRECT(\"S\" & ROW()-1)),=SUM(T1:INDIRECT(\"T\" & ROW()-1)),=SUM(U1:INDIRECT(\"U\" & ROW()-1)),," >> $STATS_FILE
echo "NUMBER OF METHODS,=ROW()-3" >> $STATS_FILE
echo "NUMBER OF THROWS CONDITIONS,=INDIRECT(\"D\" & ROW()-2)+INDIRECT(\"E\" & ROW()-2)+INDIRECT(\"F\" & ROW()-2)" >> $STATS_FILE
echo "THROWS PRECISION,=INDIRECT(\"D\" & ROW()-3)/(INDIRECT(\"D\" & ROW()-3) + INDIRECT(\"E\" & ROW()-3))" >> $STATS_FILE
echo "THROWS RECALL,=INDIRECT(\"D\" & ROW()-4)/INDIRECT(\"B\" & ROW()-2)" >> $STATS_FILE
echo "NUMBER OF PARAM CONDITIONS,=INDIRECT(\"I\" & ROW()-5)+INDIRECT(\"J\" & ROW()-5)+INDIRECT(\"K\" & ROW()-5)" >> $STATS_FILE
echo "PARAM PRECISION,=INDIRECT(\"I\" & ROW()-6)/(INDIRECT(\"I\" & ROW()-6) + INDIRECT(\"J\" & ROW()-6))" >> $STATS_FILE
echo "PARAM RECALL,=INDIRECT(\"I\" & ROW()-7)/INDIRECT(\"B\" & ROW()-2)" >> $STATS_FILE
echo "NUMBER OF RETURN CONDITIONS,=INDIRECT(\"N\" & ROW()-8)+INDIRECT(\"O\" & ROW()-8)+INDIRECT(\"P\" & ROW()-8)" >> $STATS_FILE
echo "RETURN PRECISION,=INDIRECT(\"N\" & ROW()-9)/(INDIRECT(\"N\" & ROW()-9) + INDIRECT(\"O\" & ROW()-9))" >> $STATS_FILE
echo "RETURN RECALL,=INDIRECT(\"N\" & ROW()-10)/INDIRECT(\"B\" & ROW()-2)" >> $STATS_FILE
echo "NUMBER OF CONDITIONS,=INDIRECT(\"S\" & ROW()-11)+INDIRECT(\"T\" & ROW()-11)+INDIRECT(\"U\" & ROW()-11)" >> $STATS_FILE
echo "OVERALL PRECISION,=INDIRECT(\"S\" & ROW()-12)/(INDIRECT(\"S\" & ROW()-12) + INDIRECT(\"T\" & ROW()-12))" >> $STATS_FILE
echo "OVERALL RECALL,=INDIRECT(\"S\" & ROW()-13)/INDIRECT(\"B\" & ROW()-2)" >> $STATS_FILE

echo "Open the result file: $STATS_FILE"
